TMBF: Rewrite setup_tunemeasurement for new TMBF
git-svn-id: svn+ssh://serv2/home/subversion/repos/controls/diamond/trunk/ioc/TMBF@103032 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/opi/scripts/setup_tunemeasurement b/opi/scripts/setup_tunemeasurement
--- a/opi/scripts/setup_tunemeasurement
+++ b/opi/scripts/setup_tunemeasurement
@@ -1,7 +1,23 @@
-#!/bin/sh
+#!/bin/bash
 
 # Simple script for setting the TMBF into the appropriate tune measurement
 # mode.
+
+set -e      # Exit immediately if any command fails
+
+
+Error()
+{
+    echo >&2 "$@"
+    exit 1
+}
+
+put()
+{
+    [[ -n $2 ]]  ||  Error "Missing value for $1"
+    caput -s $DEVICE:$1 "$2"
+}
+
 
 HERE="$(dirname "$0")"
 
@@ -9,149 +25,119 @@ DEVICE="${1:?Specify device}"
 MODE="${2:?Specify mode}"
 CONFIG="${3:-/home/ops/diagnostics/concentrator/TMBF_tune.config}"
 
+
 HARMONIC=80
 BUNCH=450
 
-# Pull in configured tune settings
+# Determine the nominal tune
+sweep_range=0.05
+alarm_range=0.01
+
+case $DEVICE in
+    SR21C-DI-TMBF-01)   AXIS=X ;;
+    SR21C-DI-TMBF-02)   AXIS=Y ;;
+    TS-DI-TMBF-01)      AXIS=X ;;
+    *)                  Error Unknown device $DEVICE ;;
+esac
+
+
+# Pull in configured tune settings.  The config file contains settings for tune
+# and FIR fraction cycles/length for each ring mode and axis.
 . "$CONFIG"
 
-[ $MODE = SBFB ]  &&  HARMONIC=0
+# Extract the tune settings appropriate to our device
+ring_mode=$(caget -t SR-CS-RING-01:MODE | sed 's/ $//')
+eval tune=\$${AXIS}_tune_$ring_mode
+eval cycles=\$${AXIS}_cycles_$ring_mode
+eval length=\$${AXIS}_length_$ring_mode
+if [ -z "$tune" -o -z "$cycles" -o -z "$length" ]; then
+    Error "Unknown ring mode $ring_mode, check PV SR-CS-RING-01:MODE"
+fi
+tune=0.$tune
 
 
-bb_func()
-{
-    echo -n 936
-    for ((i=0; i<936; i++)); do
-        echo -n ' '
-        if ((i == $3)); then
-            echo -n $2
-        else
-            echo -n $1
-        fi
-    done
-    echo
-}
+# Settings with mode specific overrides
+dac_output=0                # By default DAC output is off
+bunch_mode='All Bunches'    # By default detect on all bunches
+detector_input=FIR
 
-put()
-{
-    caput -w 5 -s $DEVICE:$1 "$2"
-}
-
-
-# Sets the range of tunes.  Called as:
-#
-#   set_tune <centre_freq> <sweep_range> <alarm_range>
-#
-set_tune()
-{
-    STARTFREQ=$(printf .%04d $(($1-$2)))
-    STOPFREQ=$(printf .%04d $(($1+$2)))
-    LOW=$(printf .%04d $(($1-$3)))
-    HIGH=$(printf .%04d $(($1+$3)))
-}
-
-
-# Determine the nominal tune
-sweep_range=500     # 0.05
-alarm_range=100     # 0.10
-
-# Called with $1 = X or Y, sets up tune, cycles, length
-set_computed_tune()
-{
-    mode=$(caget -t SR-CS-RING-01:MODE | sed 's/ $//')
-    eval tune=\$$1_tune_$mode
-    eval cycles=\$$1_cycles_$mode
-    eval length=\$$1_length_$mode
-
-    if [ -z "$tune" -o -z "$cycles" -o -z "$length" ]; then
-        echo >&2 "Don't recognise mode $mode"
-        echo >&2 "Check configuration in $CONFIG"
-        echo >&2 "Check PV SR-CS-RING-01:MODE"
-    else
-        set_tune $tune $sweep_range $alarm_range
-        put FIRCYCLES_S $cycles
-        put FIRLENGTH_S $length
-    fi
-}
-
-
-# Control features different in AP mode, including Tune frequency range.
+# Mode specific settings
 case $MODE in
-    TUNE|SBFB)
-        case $DEVICE in
-            SR21C-DI-TMBF-01)
-                set_computed_tune X
-                ;;
-            SR21C-DI-TMBF-02)
-                set_computed_tune Y
-                ;;
-            TS-DI-TMBF-01)
-                HARMONIC=1
-                set_tune 2500 2500 2500
-                ;;
-            *)  echo "Don't recognise that device!" >&2
-                exit 1
-        esac
-        IQSCALE=7
-        DDCINPUT=FIR
+    TUNE)   # Multibunch tune measurement
+        sweep_gain=-42dB
+        ;;
+    SBFB)   # Feedback on, single bunch tune measurement
+        sweep_gain=-24dB
+        dac_output=1    # Enable FIR output in this mode
+        bunch_mode='Single Bunch'
+        HARMONIC=0
         ;;
     AP)
-        set_tune 2500 2450 2450
-        IQSCALE=5
-        DDCINPUT=ADC
+        sweep_gain=0dB
+        tune=0.25
+        sweep_range=0.245
+        alarm_range=0.245
+        detector_input=ADC
         ;;
-    *)  echo Mode must be one of TUNE, AP or SBFB. >&2
-        exit 1
-        ;;
-esac
-
-# Control features unique to TUNE mode
-case $MODE in
-    TUNE)
-        HOMGAIN=-45dB
-        ;;
-    AP|SBFB)
-        HOMGAIN=-21dB
+    *)  Error Mode must be one of TUNE, AP or SBFB.
         ;;
 esac
 
-# Control features unique to SBFB mode
-case $MODE in
-    TUNE|AP)
-        TEMPDACOUT=HOM
-        BUNCH=1023
-        BUNCHMODE=Off
-        ;;
-    SBFB)
-        TEMPDACOUT=Off
-        BUNCHMODE=On
-        ;;
-esac
+# FIR loop delay adds an extra half FIR length
+fir_loop_delay=$(echo 1 k $length 2 / p | dc)
 
 
-put GROWDAMPMODE_S 'Off'
-put DACOUT_S 'Off'
-put TUNESWEEPMODE_S 'On'
-put PROGCLKVAL_S 25000
-put TUNESCAN.SCAN '1 second'
-put HB_BUF_LOWER.SCAN 'Passive'
-put ARCHIVE_S 'I+Q'
-put TRIGSEL_S 'Soft'
-put FIRGAIN_S '-24dB'
-put BUNCHMODE_S $BUNCHMODE
-put HOMGAIN_S $HOMGAIN
-put SWPSTARTFREQ_S $HARMONIC$STARTFREQ
-put SWPSTOPFREQ_S $HARMONIC$STOPFREQ
-put IQSCALE_S $IQSCALE
-put BUNCH_S $BUNCH
-put TEMPDACOUT_S $TEMPDACOUT
-put DDCINPUT_S $DDCINPUT
-put TUNE.HIGH $HIGH
-put TUNE.LOW $LOW
-put TUNE.HSV MINOR
-put TUNE.LSV MINOR
+# First a bunch of sanity settings, in case somebody has been messing with
+# stuff.
+put DAC:ENABLE_S Off        # Turn off while we mess with settings
 
-if [ $MODE = SBFB ]; then
-    caput -w 5 -a $DEVICE:BB_DACS_S $(bb_func 1 3 $((BUNCH-8)))
-    caput -w 5 -a $DEVICE:BB_GAINS_S $(bb_func 1 1 1)
-fi
+# Make sure we're sane.
+put LOOPBACK_S Normal
+put COMPENSATE_S Normal
+put SEQ:0:BANK_S 'Bank 0'
+put DET:RESET_WIN_S.PROC 0
+
+# Ensure no triggers are running and the sequencer is stopped
+put TRG:S1:RESET_S.PROC 0
+put TRG:S2:RESET_S.PROC 0
+put TRG:EXT:RESET_S.PROC 0
+put SEQ:RESET_S.PROC 0
+
+# Configure FIR as selected
+put FIR:0:LENGTH_S $length
+put FIR:0:CYCLES_S $cycles
+put FIR:0:USEWF_S Settings
+put FIR:GAIN_S -42dB
+
+# Configure bunch bank #0 for FIR and selected operation
+set_one_bunch $DEVICE 0 all 0 $dac_output 1023
+
+# Configure sequencer
+put SEQ:1:HOLDOFF_S 2
+put SEQ:1:DWELL_S 100
+put SEQ:1:GAIN_S $sweep_gain
+put SEQ:1:ENWIN_S Windowed
+
+# Configure detector
+put DET:MODE_S "$bunch_mode"
+put DET:AUTOGAIN_S Autogain
+put DET:INPUT_S $detector_input
+put DET:LOOP:ADC_S 1
+put DET:LOOP:FIR_S $fir_loop_delay
+
+# Configure tune measurement
+put TUNE:HARMONIC_S $HARMONIC
+put TUNE:CENTRE_S $tune
+put TUNE:RANGE_S $sweep_range
+put TUNE:ALARM_S $alarm_range
+put TUNE:BUNCH_S $BUNCH
+put TUNE:SET_S.PROC 0
+
+# Trigger on external trigger.
+put TRG:BUF:SEL_S External
+put TRG:SEQ:ENA_S Enabled
+put TRG:EXT:MODE_S Retrigger
+
+# Now we can go!
+put DAC:ENABLE_S On
+put TRG:EXT:ARM_S.PROC 0
